sudo: false
before_install:
- export HOME=`pwd`
- cd adaptive-fx
- export CURRENT_TAG=`git describe --abbrev=0`
- export CURRENT_TAG=`echo ${CURRENT_TAG//[v]/ }`
language: java
jdk:
  - oraclejdk8
install: echo "Installing"
after_success: |-
  if [ "$TRAVIS_BRANCH" == "$TRAVIS_TAG" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    echo "Releasing successful build."
    ./gradlew uploadArchives
    ./gradlew nexusStagingRelease
  elif [ "$TRAVIS_PULL_REQUEST" == "true" ]; then
    echo "Processed successful build after pull."
  fi
before_deploy:
- ./gradlew distZip
- ls -lart $HOME/adaptive-fx/adaptive-arp-fx-impl-nibble/build/distributions/
deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file: "${HOME}/adaptive-fx/adaptive-arp-fx-impl-nibble/build/distributions/adaptive-arp-fx-impl-nibble-all-${CURRENT_TAG}.zip"
  skip_cleanup: true
  on:
    tags: false